[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_program = "Esv9oAmS2gBBd9ART15jpvWknZb6bmePFAr7jKbJoKQe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dre/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
